spark.master=local[*]

spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension

spark.jars.packages=io.delta:delta-spark_2.13:4.1.0,io.unitycatalog:unitycatalog-spark_2.13:0.4.0
spark.jars.ivy=/opt/spark/jars/.ivy2

spark.sql.catalog.spark_catalog=io.unitycatalog.spark.UCSingleCatalog

spark.sql.catalog.imc_prosperity=io.unitycatalog.spark.UCSingleCatalog
spark.sql.catalog.imc_prosperity.uri=http://server:8080
spark.sql.catalog.imc_prosperity.token=""

spark.sql.defaultCatalog=imc_prosperity