[project]
name = "frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "data-platform-sdk",
    "pydantic-settings>=2.13.1",
    "streamlit>=1.55.0",
    "plotly>=6.6.0",
]

[tool.uv.sources]
data-platform-sdk = { path="../libs/data-platform-py", editable=true }
