name: unitycatalog

services:
  server:
    image: docker.io/unitycatalog/unitycatalog:main
    ports:
      - "8080:8080"
    command: >
      sh -c "./bin/start-uc-server &
             sleep 15 &&
             ./bin/uc catalog create --name imc_prosperity &&
             ./bin/uc schema create --catalog imc_prosperity --name bronze &&
             ./bin/uc schema create --catalog imc_prosperity --name silver &&
             ./bin/uc schema create --catalog imc_prosperity --name gold
             wait"
    volumes:
      - ./etc/conf/server.properties:/home/unitycatalog/etc/conf/server.properties
#      - unitycatalog_data:/home/unitycatalog/etc/data
  unity-ui:
    image: docker.io/unitycatalog/unitycatalog-ui:main
    ports:
      - "3000:3000"
    depends_on:
      - server

#volumes:
#  # Persist docker volume across container restarts
#  unitycatalog_data: